version: "3"
services:
  backend:
    build: ./backend
    ports:
      - 5001:5001
    restart: always

  proxy:
    # image: nginx:stable-alpine
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro