version: "3"
services:
    backend:
        build: ./backend
        ports:
            - 5001:5001
        restart: always
    backend2:
        build: ./backend2
        ports:
            - 5002:5002
        restart: always
    proxy:
    # image: nginx:stable-alpine
        build: ./nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - backend
            - backend2
    master:
        image: locustio/locust
        ports:
            - "8089:8089"
        volumes:
            - ./:/mnt/locust
        command: -f /mnt/locust/locustfile.py --master -H http://master:8089
        depends_on:
            - proxy

    worker:
        image: locustio/locust
        volumes:
            - ./:/mnt/locust
        command: -f /mnt/locust/locustfile.py --worker --master-host master
        depends_on:
            - proxy