version: "3"
services:
    backend:
        build: ./backend
        ports:
            - 5001:5001
        restart: always
        depends_on:
            - backend
    proxy:
    # image: nginx:stable-alpine
        build: ./nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - backend
    locust:
        build: ./locust
        restart: always
        ports:
            - 8089:8089
        depends_on:
            - backend
            - proxy